version: 1.0.{build}
configuration: Release
platform: Any CPU
cache:
- .paket -> paket.lock
- packages -> paket.lock
build:
  verbosity: minimal

on_failure:
  - appveyor PushArtifact artifacts\LiveErrorsWindow_start.png
  - appveyor PushArtifact artifacts\LiveErrorsWindow_finish.png
  - appveyor PushArtifact artifacts\ScopeIsErrorScopeWindow_start.png
  - appveyor PushArtifact artifacts\ScopeIsErrorScopeWindow_finish.png
  - appveyor PushArtifact artifacts\ScopeTextBoxWindow_start.png
  - appveyor PushArtifact artifacts\ScopeTextBoxWindow_finish.png
